name: Docker Images
on:
  # This workflow should be triggered by pushes to micro/micro main branch
  # It builds the docker images as required by m3o
  repository_dispatch:
    types: [micro_release]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Clone micro repo
        uses: actions/checkout@v2
        with:
          repository: 'micro/micro'

      - name: Fetch tags
        run: git fetch --prune --unshallow

      - name: Replace platform profile
        id: replace-profile
        run: |
          go mod edit -replace github.com/micro/micro/plugin/etcd/v3=./plugin/etcd
          go mod edit -replace github.com/micro/micro/plugin/cockroach/v3=./plugin/cockroach
          go mod edit -replace github.com/micro/micro/plugin/prometheus/v3=./plugin/prometheus
          go mod edit -replace github.com/micro/micro/plugin/nats/broker/v3=./plugin/nats/broker
          go mod edit -replace github.com/micro/micro/plugin/nats/stream/v3=./plugin/nats/stream
          go mod edit -replace github.com/micro/micro/profile/platform/v3=./profile/platform
          go mod edit -replace google.golang.org/grpc=google.golang.org/grpc@v1.26.0

      - name: Build profile
        run: |
          go run . init --profile=platform --output=profile.go

      - name: Publish to platform image to registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: m3o/platform
          username: ${{ secrets.GHCR_ACTOR }}
          password: ${{ secrets.GHCR_PAT }}
          snapshot: true
          registry: ghcr.io

      - name: Build and push cells to registry
        run: cd service/runtime/cells; bash build.sh
        env:
          USERNAME: ${{ secrets.GHCR_ACTOR }}
          PASSWORD: ${{ secrets.GHCR_PAT }}
          DOCKER_DOMAIN: ghcr.io
          IMAGE: m3o/cells
